### ISSUE TITLE
进入房间黑屏

### ISSUE THREAD

**Issue by hifor** [TencentVideoCloudMLVBDev/webrtc_web_source#1]
![](http://7xjzgy.com1.z0.glb.clouddn.com/github/ik_20180712160737.png)
```json
{
    errorCode:-2,
    errorMsg:"verify sig,udp send error!"
}
```

![](http://7xjzgy.com1.z0.glb.clouddn.com/github/ik_20180712164626.png)

**Comment by hifor** [comment]
经常报mainwindow.js:513 ENTER RTC ROOM failed
然后又自动退出房间

{errorCode: -10010, errorMsg: "create room error!!! e = undefined"}

{"ActionStatus":"FAIL","ErrorCode":60008,"ErrorInfo":"service timeout or request format error,please check and try again"}


这异常提示就是个坑，看了下在线体验的，发现WebRTCAPI.min.js 用的版本是2.2的
https://sqimg.qq.com/expert_qq/webrtc/2.2/WebRTCAPI.min.js

然后我把搭在服务器上的也改成这个版本，最后提示异常信息：
{errorCode: 11000, errorMsg: "verify sig failed with info: [appid no in white err]"}

查了错误文档：
https://cloud.tencent.com/document/product/647/17016


| Key        | 错误码  | 错误类型 |    描述      |
| :-------- | :--------:| :---------: | :---------: |
| NOT_IN_WHITE_LIST | 11000 | SdkAppid不在白名单 | 排查步骤: step1. sdkappid 是否填写正确（1400xxxxxx） step2.确认一下您是否开通了TRTC服务（购买任意套餐均可开通），没有开通服务的情况下，您不能使用自己的sdkappid。|

好吧，意思是要先交钱，对开发人员真不友好，折腾半天都没了解到实际功能是否满足我们开发需要，结果就给两字“给钱”！！！！

**Comment by zhurongheng** [comment]
买了1元测试，然而没啥用，2.2提示不在白名单，2.4，ENTER RTC ROOM failed，没法用。

**Comment by rackeyyang** [comment]
@zhurongheng 
可否提供一下sdkappid

**Comment by zhurongheng** [comment]
@rackeyyang 
1400117800

**Comment by rackeyyang** [comment]
@zhurongheng  
白名单开通了的，有半小时-两小时的生效时间，稍后再试一下。
